# Generated by Django 5.1.3 on 2024-11-14 17:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0005_remove_post_artist_remove_post_title_remove_post_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
