# Generated by Django 5.1 on 2024-09-10 19:25

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='avatars/'),
        ),
    ]
