# Generated by Django 5.1.1 on 2024-10-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_landingpages', '0002_landingpage_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
