# Generated by Django 5.1 on 2024-09-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='production_enable',
            new_name='production_enabled',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='staging_enable',
            new_name='staging_enabled',
        ),
    ]
